Add comment issues8
SpaceyaTech/blog pull request #13
Opened 2023-02-08 17:34 UTC by Msdot001

# Description

Create a Comment model and test the model using a unit test 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-02-08 17:39 UTC, Msdot001 commented
creation and testing of a comment model.

2023-02-13 00:01 UTC, aibunny submitted a review, later dismissed

2023-02-15 11:41 UTC, Barissa-Imran requested changes
From the meeting, we agreed that we are to use the pytest module for running our tests. Please see: 
- [Pytest](https://pytest.org/)

How we have used it before:
- [account tests](https://github.com/SpaceyaTech/blog/blob/main/CMS/tests/accounts/test_account_serializers.py)

Also check for any conflicts you might be getting from this pr

2023-02-15 11:44 UTC, JimmyTron approved these changes

2023-02-15 11:44 UTC, JimmyTron commented on blog/admin.py
> +
I see it

2023-02-15 11:44 UTC, Msdot001 commented
Okay.

I will work on it. Thanks


On Wed 15. Feb 2023 at 12:41, Imran ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> From the meeting, we agreed that we are to use the pytest module for
> running our tests. Please see:
>
>    - Pytest <https://pytest.org/>
>
> How we have used it before:
>
>    - account tests
>    <https://github.com/SpaceyaTech/blog/blob/main/CMS/tests/accounts/test_account_serializers.py>
>
> Also check for any conflicts you might be getting from this pr
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SpaceyaTech/blog/pull/13#pullrequestreview-1299330230>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXR5YHFLA6SBAISSUGF365DWXS6G5ANCNFSM6AAAAAAUVRQSIM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-17 17:52 UTC, IanoNjuguna submitted a review, later dismissed

2023-02-23 19:43 UTC, IanoNjuguna approved these changes

2023-02-24 12:57 UTC, JimmyTron approved these changes

2023-03-18 06:03 UTC, closed without merging