Add Date Published feature to blog
SpaceyaTech/blog pull request #18
Opened 2023-02-22 10:24 UTC by Collins-Omariba

# Description

Added  status ,published_date fields and publish function for the Stori model , plus a view to change the status to published with its corresponding url path.

Fixes #17 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-22 11:17 UTC, JimmyTron requested changes
Just a minor adjustment it all fine. 👍👍

2023-02-22 11:17 UTC, JimmyTron commented on blog/models.py
> +        ('drafted', 'drafted'),
Change to 'draft' instead

2023-02-22 11:17 UTC, JimmyTron commented on blog/models.py
> +    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='drafted')
Use draft.

2023-02-22 12:11 UTC, hellen-22 submitted a review, later dismissed

2023-02-22 13:51 UTC, Collins-Omariba commented on blog/models.py
> +    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='drafted')
Done

2023-02-22 13:59 UTC, Collins-Omariba commented on blog/models.py
> +        ('drafted', 'drafted'),
Done

2023-02-22 14:12 UTC, aibunny commented
Nice implementation

2023-02-22 15:00 UTC, Collins-Omariba commented
> Nice implementation

Thanks 👍

2023-02-23 06:40 UTC, hellen-22 approved these changes

2023-02-24 12:55 UTC, merged